version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
      BETTER_AUTH_SECRET: supersecret-supersecret-supersecret-supersecret
      BETTER_AUTH_URL: http://localhost:3000
      BETTER_AUTH_TRUSTED_ORIGINS: http://localhost:3000
      ADMIN_SEED_KEY: seed-admin-2024
      ADMIN_EMAIL: admin@cornia.co
      ADMIN_PASSWORD: Admin123!
      ADMIN_PHONE: '+8801784176442'
      ADMIN_NAME: 'Demo Admin'
    depends_on:
      - db
    command: pnpm dev

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
